home/urls.py
from django.urls import path

from home.views import (
    index,
    offer_board,
    deal_progression_overview,
    employee_valuation_list,
    employee_instruction_list,
    employee_reduction_list,
    employee_new_business_list,
    add_primary_processor,
    lettings_add_primary_processor,
)


app_name = "home"
urlpatterns = [
    path("", index, name="home"),
    path("properties/offer-board/", offer_board, name="offer_board"),
    path(
        "progression/",
        deal_progression_overview,
        name="deal_progression_overview",
    ),
    path(
        "ajax/valuations/<profile_id>/",
        employee_valuation_list,
        name="employee_valuation_list",
    ),
    path(
        "ajax/instructions/<profile_id>/",
        employee_instruction_list,
        name="employee_instruction_list",
    ),
    path(
        "ajax/reductions/<profile_id>/",
        employee_reduction_list,
        name="employee_reduction_list",
    ),
    path(
        "ajax/new-business/<profile_id>/",
        employee_new_business_list,
        name="employee_new_business_list",
    ),
    path(
        "ajax/primary-progressor/<propertyprocess_id>/",
        add_primary_processor,
        name="add_primary_processor",
    ),
    path(
        "ajax/lettings-primary-progressor/<propertyprocess_id>/",
        lettings_add_primary_processor,
        name="lettings_add_primary_processor",
    ),
]

properties/urls.py
from django.urls import path

from properties.views import (
    property_list,
    property_detail,
    property_history_pagination,
    property_history_detail,
    offer_history,
    offer_history_lettings,
    offers_pagination,
    notes_pagination,
    save_property_order,
    property_chain_detail,
    render_property,
    validate_property_address,
    add_property,
    add_propertyprocess,
    add_valuation,
    add_instruction,
    add_lettings_instruction,
    render_history_notes,
    add_history_notes,
    add_reduction,
    add_offerer,
    add_offerer_mortgage,
    add_offerer_cash,
    add_offerer_lettings,
    add_offer,
    add_offer_form,
    add_offer_lettings,
    add_another_offer,
    add_another_lettings_offer,
    edit_offerer_cash,
    edit_offerer_mortgage,
    edit_offer_status,
    edit_offer_lettings_status,
    edit_instruction,
    edit_instruction_change,
    withdraw_property,
    back_on_the_market,
    re_let,
    add_deal,
    add_deal_lettings,
    edit_deal,
    add_exchange,
    add_exchange_lettings,
    edit_sales_prog_settings,
    phase_one,
    phase_two,
    phase_three,
    phase_four,
    add_client_info,
    edit_client_info,
    edit_progression_notes,
    add_progression_notes,
    delete_progression_notes,
    add_property_chain_detail,
    edit_property_chain_detail,
    delete_property_chain_detail,
    fall_through,
    manage_sales_progression,
    edit_lettings_prog_settings,
    lettings_phase_one,
    lettings_phase_two,
    lettings_phase_three,
    lettings_phase_four,
    add_eicr_info,
    edit_eicr_info,
    add_epc_info,
    edit_epc_info,
    add_gsc_info,
    edit_gsc_info,
    add_inventory_info,
    edit_inventory_info,
    add_cleaning_info,
    edit_cleaning_info,
    waiting_on_chain,
    delete_offerer,
    delete_offerer_lettings,
    lettings_fall_through,
)


app_name = "properties"
urlpatterns = [
    path("properties/", property_list, name="property_list"),
    path(
        "properties/<propertyprocess_id>/",
        property_detail,
        name="property_detail",
    ),
    path(
        "properties/history/<propertyprocess_id>/pagination/",
        property_history_pagination,
        name="property_history_pagination",
    ),
    path(
        "properties/history/<property_history_id>/",
        property_history_detail,
        name="property_history_instance",
    ),
    path(
        "properties/offers/<propertyprocess_id>/pagination/",
        offers_pagination,
        name="offers_pagination",
    ),
    path(
        "properties/notes/<propertyprocess_id>/pagination/",
        notes_pagination,
        name="notes_pagination",
    ),
    path(
        "properties/offers/<offerer_id>/",
        offer_history,
        name="offerer_offers",
    ),
    path(
        "properties/offers-lettings/<offerer_id>/",
        offer_history_lettings,
        name="offerer_offers_lettings",
    ),
    path(
        "properties/property-chain/new-order/",
        save_property_order,
        name="save_property_order",
    ),
    path(
        "properties/property-chain/new-order/<property_chain_id>/",
        property_chain_detail,
        name="property_chain_detail",
    ),
    path(
        "properties/add/property-chain/<propertyprocess_id>/",
        add_property_chain_detail,
        name="add_property_chain_detail",
    ),
    path(
        "properties/edit/property-chain/<property_chain_id>/",
        edit_property_chain_detail,
        name="edit_property_chain_detail",
    ),
    path(
        "properties/delete/property-chain/<property_chain_id>/",
        delete_property_chain_detail,
        name="delete_property_chain_detail",
    ),
    path(
        "properties/render/property/",
        render_property,
        name="render_property",
    ),
    path(
        "properties/add/property/",
        add_property,
        name="add_property",
    ),
    path(
        "properties/add/property-process/<property_id>/",
        add_propertyprocess,
        name="add_property_process",
    ),
    path(
        "properties/validate/address/",
        validate_property_address,
        name="validate_property_address",
    ),
    path(
        "properties/add/valuation/<propertyprocess_id>/",
        add_valuation,
        name="add_valuation",
    ),
    path(
        "properties/render/history-notes/<history_id>/",
        render_history_notes,
        name="render_history_notes",
    ),
    path(
        "properties/add/history-notes/<history_id>/",
        add_history_notes,
        name="add_history_notes",
    ),
    path(
        "properties/add/instruction/<propertyprocess_id>/",
        add_instruction,
        name="add_instruction",
    ),
    path(
        "properties/add/instruction-lettings/<propertyprocess_id>/",
        add_lettings_instruction,
        name="add_lettings_instruction",
    ),
    path(
        "properties/add/reduction/<propertyprocess_id>/",
        add_reduction,
        name="add_reduction",
    ),
    path(
        "properties/add/offerer/<propertyprocess_id>/",
        add_offerer,
        name="add_offerer",
    ),
    path(
        "properties/add/offerer-lettings/<propertyprocess_id>/",
        add_offerer_lettings,
        name="add_offerer_lettings",
    ),
    path(
        "properties/add/offerer-mortgage/<propertyprocess_id>/<offerer_id>/",
        add_offerer_mortgage,
        name="add_offerer_mortgage",
    ),
    path(
        "properties/add/offerer-cash/<propertyprocess_id>/<offerer_id>/",
        add_offerer_cash,
        name="add_offerer_cash",
    ),
    path(
        "properties/add/offer/<propertyprocess_id>/<offerer_id>/",
        add_offer,
        name="add_offer",
    ),
    path(
        "properties/add/offer-form/<propertyprocess_id>/<offerer_id>/",
        add_offer_form,
        name="add_offer_form",
    ),
    path(
        "properties/add/offer-lettings/<propertyprocess_id>/<offerer_id>/",
        add_offer_lettings,
        name="add_offer_lettings",
    ),
    path(
        "properties/add/another-offer/<propertyprocess_id>/",
        add_another_offer,
        name="add_another_offer",
    ),
    path(
        "properties/add/another-offer-lettings/<propertyprocess_id>/",
        add_another_lettings_offer,
        name="add_another_lettings_offer",
    ),
    path(
        "properties/edit/offerer-cash/<offerer_id>/",
        edit_offerer_cash,
        name="edit_offerer_cash",
    ),
    path(
        "properties/edit/offerer-mortgage/<offerer_id>/",
        edit_offerer_mortgage,
        name="edit_offerer_mortgage",
    ),
    path(
        "properties/edit/offer-status/<offer_id>/",
        edit_offer_status,
        name="edit_offer_status",
    ),
    path(
        "properties/edit/offer-status-lettings/<offer_id>/",
        edit_offer_lettings_status,
        name="edit_offer_lettings_status",
    ),
    path(
        "properties/edit/instruction/<propertyprocess_id>/",
        edit_instruction,
        name="edit_instruction",
    ),
    path(
        "properties/edit/instruction-change/<instruction_change_id>/",
        edit_instruction_change,
        name="edit_instruction_change",
    ),
    path(
        "properties/withdraw/<propertyprocess_id>/",
        withdraw_property,
        name="withdraw_property",
    ),
    path(
        "properties/re-let/<propertyprocess_id>/",
        back_on_the_market,
        name="back_on_the_market",
    ),
    path(
        "properties/back-on-market/<propertyprocess_id>/",
        re_let,
        name="re_let",
    ),
    path(
        "properties/add/deal/<propertyprocess_id>/",
        add_deal,
        name="add_deal",
    ),
    path(
        "properties/add/deal-lettings/<propertyprocess_id>/",
        add_deal_lettings,
        name="add_deal_lettings",
    ),
    path(
        "properties/edit/deal/<propertyprocess_id>/",
        edit_deal,
        name="edit_deal",
    ),
    path(
        "properties/add/exchange/<propertyprocess_id>/",
        add_exchange,
        name="add_exchange",
    ),
    path(
        "properties/add/exchange-lettings/<propertyprocess_id>/",
        add_exchange_lettings,
        name="add_exchange_lettings",
    ),
    path(
        "properties/edit/sales-progression/settings/<propertyprocess_id>/",
        edit_sales_prog_settings,
        name="edit_sales_prog_settings",
    ),
    path(
        "properties/edit/sales-progression/phase-one/<propertyprocess_id>/",
        phase_one,
        name="phase_one",
    ),
    path(
        "properties/edit/sales-progression/phase-two/<propertyprocess_id>/",
        phase_two,
        name="phase_two",
    ),
    path(
        "properties/edit/sales-progression/phase-three/<propertyprocess_id>/",
        phase_three,
        name="phase_three",
    ),
    path(
        "properties/edit/sales-progression/phase-four/<propertyprocess_id>/",
        phase_four,
        name="phase_four",
    ),
    path(
        "properties/edit/lettings-progression/settings/<propertyprocess_id>/",
        edit_lettings_prog_settings,
        name="edit_lettings_prog_settings",
    ),
    path(
        "properties/edit/lettings-progression/phase-one/<propertyprocess_id>/",
        lettings_phase_one,
        name="lettings_phase_one",
    ),
    path(
        "properties/edit/lettings-progression/phase-two/<propertyprocess_id>/",
        lettings_phase_two,
        name="lettings_phase_two",
    ),
    path(
        "properties/edit/lettings-progression/phase-three/<propertyprocess_id>/",
        lettings_phase_three,
        name="lettings_phase_three",
    ),
    path(
        "properties/edit/lettings-progression/phase-four/<propertyprocess_id>/",
        lettings_phase_four,
        name="lettings_phase_four",
    ),
    path(
        "properties/add/sales-progression/client-info/<propertyprocess_id>/",
        add_client_info,
        name="add_client_info",
    ),
    path(

properties/templates/properties/stages/add_another_lettings_offer_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Change Offer</h4>
            <form method="post" action="{% url 'properties:add_another_lettings_offer' propertyprocess_id %}" class="text-center text-white px-2 js-submit-form-success custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.offerer_lettings_details|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.offer|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.status|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form_lettings.proposed_move_in_date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form_lettings.term|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Change Offer" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

properties/templates/properties/stages/add_another_offer_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Change Offer</h4>
            <form method="post" action="{% url 'properties:add_another_offer' propertyprocess_id %}" class="text-center text-white px-2 js-submit-form-success custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.offerer_details|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.offer|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.status|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Change Offer" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

properties/templates/properties/stages/add_deal_lettings_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add Deal</h4>
            <p class="text-white text-center">Please select the offer that is being accepted and proceed with the deal. Please note, adding a deal can take a number of seconds to process, please be patient.</p>
            <form method="post" action="{% url 'properties:add_deal_lettings' propertyprocess_id %}" class="text-center text-white px-2 js-submit-form-success custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.offer_accepted|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.target_move_date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ deal_extra_form.term|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ deal_extra_form.break_clause|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ marketing_form.applicant_intro|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ marketing_board_form.sold_marketing_board|as_crispy_field }}
                    </div>
                </div>

                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Add Deal" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

properties/templates/properties/stages/add_deal_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add Deal</h4>
            <p class="text-white text-center">Please select the offer that is being accepted and proceed with the deal. Please note, adding a deal can take a number of seconds to process, please be patient.</p>
            <form method="post" action="{% url 'properties:add_deal' propertyprocess_id %}" class="text-center text-white px-2 js-submit-form-success custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.offer_accepted|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.target_move_date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ marketing_form.applicant_intro|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ marketing_board_form.sold_marketing_board|as_crispy_field }}
                        <small id="hint_id_sold_marketing_board" class="form-text text-white">*** Default To Current Board ***</small>
                    </div>
                </div>

                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Add Deal" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

properties/templates/properties/stages/add_instruction_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add Instruction</h4>
            <form method="post" action="{% url 'properties:add_instruction' propertyprocess_id%}" class="text-center text-white px-2 js-submit-form-success custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 col-sm-6 offset-sm-3">
                        {{ form.agreement_type|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-6">
                        {{ form.length_of_contract|as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ form.date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-6">
                        {{ form.listing_price|as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ form.fee_agreed|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-6">
                        {{ form.marketing_board|as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ floor_space_form.floor_space|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ instruction_reason_form.why_did_they_instruct_us|as_crispy_field }}
                    </div>
                    <div class="col-12">
                        {{ instruction_reason_form.other|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Add Instruction" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

properties/templates/properties/stages/add_offer_lettings_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add New Offer</h4>
            <p class="text-white text-center">Please add the offer made by {{ offerer.full_name }}.</p>
            <form method="post" action="{% url 'properties:add_offer_lettings' propertyprocess_id offerer.id %}" class="text-center text-white px-2 js-submit-form-success custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.offer|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.status|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form_lettings.proposed_move_in_date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form_lettings.term|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Add New Offer" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

properties/templates/properties/stages/add_offerer_lettings_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add New Offerer</h4>
            <form method="post" action="{% url 'properties:add_offerer_lettings' propertyprocess_id%}" class="text-center text-white px-2 js-add-offerer-lettings-form custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.full_name|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 mt-1">
                        <label for="id_completed_offer_form" class="form-check-label requiredField">
                            Completed Offer Form?<span class="asteriskField">*</span>
                        </label>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="id_completed_offer_form" name="completed_offer_form">
                            <label class="form-check-label" for="id_completed_offer_form">Completed</label>
                        </div>
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Add New Offerer" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

properties/templates/properties/stages/add_offerer_mortgage_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add Offerer Mortgage Details</h4>
            <form method="post" action="{% url 'properties:add_offerer_mortgage' propertyprocess_id offerer_id %}" class="text-center text-white px-2 js-add-offerer-mortgage-form custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.deposit_percentage|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.verified_status|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Add Mortgage Info" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

properties/templates/properties/stages/add_property_and_valuation_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add Property & Valuation</h4>
            <div class="row px-2 py-0">
                <div class="col-12 col-md-6 offset-md-3 mb-1">
                    <select class="get-address-select2 text-muted"></select>
                </div>
            </div>
            <form method="post" action="{% url 'properties:add_property' %}" class="text-center text-white p-2 js-add-property custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 col-sm-6">
                        {{ form.address_line_1|as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ form.address_line_2|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-6">
                        {{ form.town|as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ form.postcode|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-6">
                        {{ form.property_type|as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ form.property_style|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-6">
                        {{ form.number_of_bedrooms|as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ form.tenure|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-6 offset-md-3 mb-1">
                        {{ process_form.sector|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-6">
                        {{ process_form.employee|as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ process_form.hub|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center" id="submit-section">
                    <div class="d-none" id="alert-div">
                        {% include 'properties/stages/includes/property_in_system.html' %}
                    </div>
                    <button type="submit" class="btn btn-info" id="add-button" disabled>{% trans "Save & Go To Valuation" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{{ get_address_api_key|json_script:"id_get_address_api_key" }}
<!-- /.modal-content -->

properties/templates/properties/stages/edit_offer_status_lettings_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Edit Offer</h4>
            <p class="text-white text-center">Please update the offer status.</p>
            <form method="post" action="{% url 'properties:edit_offer_lettings_status' offer.id %}" class="text-center text-white px-2 js-submit-form-success custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.status|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Update Offer Status" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->