home/urls.py
from django.urls import path

from home.views import (
    index,
    offer_board,
    deal_progression_overview,
    employee_valuation_list,
    employee_instruction_list,
    employee_reduction_list,
    employee_new_business_list,
    add_primary_processor,
    lettings_add_primary_processor,
)


app_name = "home"
urlpatterns = [
    path("", index, name="home"),
    path("properties/offer-board/", offer_board, name="offer_board"),
    path(
        "progression/",
        deal_progression_overview,
        name="deal_progression_overview",
    ),
    path(
        "ajax/valuations/<profile_id>/",
        employee_valuation_list,
        name="employee_valuation_list",
    ),
    path(
        "ajax/instructions/<profile_id>/",
        employee_instruction_list,
        name="employee_instruction_list",
    ),
    path(
        "ajax/reductions/<profile_id>/",
        employee_reduction_list,
        name="employee_reduction_list",
    ),
    path(
        "ajax/new-business/<profile_id>/",
        employee_new_business_list,
        name="employee_new_business_list",
    ),
    path(
        "ajax/primary-progressor/<propertyprocess_id>/",
        add_primary_processor,
        name="add_primary_processor",
    ),
    path(
        "ajax/lettings-primary-progressor/<propertyprocess_id>/",
        lettings_add_primary_processor,
        name="lettings_add_primary_processor",
    ),
]

properties/urls.py
from django.urls import path

from properties.views import (
    property_list,
    property_detail,
    property_history_pagination,
    property_history_detail,
    offer_history,
    offer_history_lettings,
    offers_pagination,
    notes_pagination,
    save_property_order,
    property_chain_detail,
    render_property,
    validate_property_address,
    add_property,
    add_propertyprocess,
    add_valuation,
    add_instruction,
    add_lettings_instruction,
    render_history_notes,
    add_history_notes,
    add_reduction,
    add_offerer,
    add_offerer_mortgage,
    add_offerer_cash,
    add_offerer_lettings,
    add_offer,
    add_offer_form,
    add_offer_lettings,
    add_another_offer,
    add_another_lettings_offer,
    edit_offerer_cash,
    edit_offerer_mortgage,
    edit_offer_status,
    edit_offer_lettings_status,
    edit_instruction,
    edit_instruction_change,
    withdraw_property,
    back_on_the_market,
    re_let,
    add_deal,
    add_deal_lettings,
    edit_deal,
    add_exchange,
    add_exchange_lettings,
    edit_sales_prog_settings,
    phase_one,
    phase_two,
    phase_three,
    phase_four,
    add_client_info,
    edit_client_info,
    edit_progression_notes,
    add_progression_notes,
    delete_progression_notes,
    add_property_chain_detail,
    edit_property_chain_detail,
    delete_property_chain_detail,
    fall_through,
    manage_sales_progression,
    edit_lettings_prog_settings,
    lettings_phase_one,
    lettings_phase_two,
    lettings_phase_three,
    lettings_phase_four,
    add_eicr_info,
    edit_eicr_info,
    add_epc_info,
    edit_epc_info,
    add_gsc_info,
    edit_gsc_info,
    add_inventory_info,
    edit_inventory_info,
    add_cleaning_info,
    edit_cleaning_info,
    waiting_on_chain,
    delete_offerer,
    delete_offerer_lettings,
    lettings_fall_through,
)


app_name = "properties"
urlpatterns = [
    path("properties/", property_list, name="property_list"),
    path(
        "properties/<propertyprocess_id>/",
        property_detail,
        name="property_detail",
    ),
    path(
        "properties/history/<propertyprocess_id>/pagination/",
        property_history_pagination,
        name="property_history_pagination",
    ),
    path(
        "properties/history/<property_history_id>/",
        property_history_detail,
        name="property_history_instance",
    ),
    path(
        "properties/offers/<propertyprocess_id>/pagination/",
        offers_pagination,
        name="offers_pagination",
    ),
    path(
        "properties/notes/<propertyprocess_id>/pagination/",
        notes_pagination,
        name="notes_pagination",
    ),
    path(
        "properties/offers/<offerer_id>/",
        offer_history,
        name="offerer_offers",
    ),
    path(
        "properties/offers-lettings/<offerer_id>/",
        offer_history_lettings,
        name="offerer_offers_lettings",
    ),
    path(
        "properties/property-chain/new-order/",
        save_property_order,
        name="save_property_order",
    ),
    path(
        "properties/property-chain/new-order/<property_chain_id>/",
        property_chain_detail,
        name="property_chain_detail",
    ),
    path(
        "properties/add/property-chain/<propertyprocess_id>/",
        add_property_chain_detail,
        name="add_property_chain_detail",
    ),
    path(
        "properties/edit/property-chain/<property_chain_id>/",
        edit_property_chain_detail,
        name="edit_property_chain_detail",
    ),
    path(
        "properties/delete/property-chain/<property_chain_id>/",
        delete_property_chain_detail,
        name="delete_property_chain_detail",
    ),
    path(
        "properties/render/property/",
        render_property,
        name="render_property",
    ),
    path(
        "properties/add/property/",
        add_property,
        name="add_property",
    ),
    path(
        "properties/add/property-process/<property_id>/",
        add_propertyprocess,
        name="add_property_process",
    ),
    path(
        "properties/validate/address/",
        validate_property_address,
        name="validate_property_address",
    ),
    path(
        "properties/add/valuation/<propertyprocess_id>/",
        add_valuation,
        name="add_valuation",
    ),
    path(
        "properties/render/history-notes/<history_id>/",
        render_history_notes,
        name="render_history_notes",
    ),
    path(
        "properties/add/history-notes/<history_id>/",
        add_history_notes,
        name="add_history_notes",
    ),
    path(
        "properties/add/instruction/<propertyprocess_id>/",
        add_instruction,
        name="add_instruction",
    ),
    path(
        "properties/add/instruction-lettings/<propertyprocess_id>/",
        add_lettings_instruction,
        name="add_lettings_instruction",
    ),
    path(
        "properties/add/reduction/<propertyprocess_id>/",
        add_reduction,
        name="add_reduction",
    ),
    path(
        "properties/add/offerer/<propertyprocess_id>/",
        add_offerer,
        name="add_offerer",
    ),
    path(
        "properties/add/offerer-lettings/<propertyprocess_id>/",
        add_offerer_lettings,
        name="add_offerer_lettings",
    ),
    path(
        "properties/add/offerer-mortgage/<propertyprocess_id>/<offerer_id>/",
        add_offerer_mortgage,
        name="add_offerer_mortgage",
    ),
    path(
        "properties/add/offerer-cash/<propertyprocess_id>/<offerer_id>/",
        add_offerer_cash,
        name="add_offerer_cash",
    ),
    path(
        "properties/add/offer/<propertyprocess_id>/<offerer_id>/",
        add_offer,
        name="add_offer",
    ),
    path(
        "properties/add/offer-form/<propertyprocess_id>/<offerer_id>/",
        add_offer_form,
        name="add_offer_form",
    ),
    path(
        "properties/add/offer-lettings/<propertyprocess_id>/<offerer_id>/",
        add_offer_lettings,
        name="add_offer_lettings",
    ),
    path(
        "properties/add/another-offer/<propertyprocess_id>/",
        add_another_offer,
        name="add_another_offer",
    ),
    path(
        "properties/add/another-offer-lettings/<propertyprocess_id>/",
        add_another_lettings_offer,
        name="add_another_lettings_offer",
    ),
    path(
        "properties/edit/offerer-cash/<offerer_id>/",
        edit_offerer_cash,
        name="edit_offerer_cash",
    ),
    path(
        "properties/edit/offerer-mortgage/<offerer_id>/",
        edit_offerer_mortgage,
        name="edit_offerer_mortgage",
    ),
    path(
        "properties/edit/offer-status/<offer_id>/",
        edit_offer_status,
        name="edit_offer_status",
    ),
    path(
        "properties/edit/offer-status-lettings/<offer_id>/",
        edit_offer_lettings_status,
        name="edit_offer_lettings_status",
    ),
    path(
        "properties/edit/instruction/<propertyprocess_id>/",
        edit_instruction,
        name="edit_instruction",
    ),
    path(
        "properties/edit/instruction-change/<instruction_change_id>/",
        edit_instruction_change,
        name="edit_instruction_change",
    ),
    path(
        "properties/withdraw/<propertyprocess_id>/",
        withdraw_property,
        name="withdraw_property",
    ),
    path(
        "properties/re-let/<propertyprocess_id>/",
        back_on_the_market,
        name="back_on_the_market",
    ),
    path(
        "properties/back-on-market/<propertyprocess_id>/",
        re_let,
        name="re_let",
    ),
    path(
        "properties/add/deal/<propertyprocess_id>/",
        add_deal,
        name="add_deal",
    ),
    path(
        "properties/add/deal-lettings/<propertyprocess_id>/",
        add_deal_lettings,
        name="add_deal_lettings",
    ),
    path(
        "properties/edit/deal/<propertyprocess_id>/",
        edit_deal,
        name="edit_deal",
    ),
    path(
        "properties/add/exchange/<propertyprocess_id>/",
        add_exchange,
        name="add_exchange",
    ),
    path(
        "properties/add/exchange-lettings/<propertyprocess_id>/",
        add_exchange_lettings,
        name="add_exchange_lettings",
    ),
    path(
        "properties/edit/sales-progression/settings/<propertyprocess_id>/",
        edit_sales_prog_settings,
        name="edit_sales_prog_settings",
    ),
    path(
        "properties/edit/sales-progression/phase-one/<propertyprocess_id>/",
        phase_one,
        name="phase_one",
    ),
    path(
        "properties/edit/sales-progression/phase-two/<propertyprocess_id>/",
        phase_two,
        name="phase_two",
    ),
    path(
        "properties/edit/sales-progression/phase-three/<propertyprocess_id>/",
        phase_three,
        name="phase_three",
    ),
    path(
        "properties/edit/sales-progression/phase-four/<propertyprocess_id>/",
        phase_four,
        name="phase_four",
    ),
    path(
        "properties/edit/lettings-progression/settings/<propertyprocess_id>/",
        edit_lettings_prog_settings,
        name="edit_lettings_prog_settings",
    ),
    path(
        "properties/edit/lettings-progression/phase-one/<propertyprocess_id>/",
        lettings_phase_one,
        name="lettings_phase_one",
    ),
    path(
        "properties/edit/lettings-progression/phase-two/<propertyprocess_id>/",
        lettings_phase_two,
        name="lettings_phase_two",
    ),
    path(
        "properties/edit/lettings-progression/phase-three/<propertyprocess_id>/",
        lettings_phase_three,
        name="lettings_phase_three",
    ),
    path(
        "properties/edit/lettings-progression/phase-four/<propertyprocess_id>/",
        lettings_phase_four,
        name="lettings_phase_four",
    ),
    path(
        "properties/add/sales-progression/client-info/<propertyprocess_id>/",
        add_client_info,
        name="add_client_info",
    ),
    path(

properties/templates/properties/includes/detail/lettings_progression.html
<div class="card">
    <div class="card-body">
        <ul class="nav nav-pills bg-nav-pills nav-justified mb-3 flex-wrap">
            <li class="nav-item">
                <a href="#overview" data-toggle="tab" aria-expanded="true" class="nav-link rounded-0 active">
                    Overview
                </a>
            </li>
            <li class="nav-item">
                <a href="#phase1" data-toggle="tab" aria-expanded="true" class="nav-link rounded-0">
                    Phase 1
                </a>
            </li>
            <li class="nav-item">
                <a href="#phase2" data-toggle="tab" aria-expanded="true" class="nav-link rounded-0">
                    Phase 2
                </a> 
            </li>
            <li class="nav-item">
                <a href="#phase3" data-toggle="tab" aria-expanded="true" class="nav-link rounded-0">
                    Phase 3
                </a>
            </li>
            <li class="nav-item">
                <a href="#phase4" data-toggle="tab" aria-expanded="true" class="nav-link rounded-0">
                    Phase 4
                </a>
            </li>

        </ul>
        <div class="tab-content">
            {% include 'properties/includes/lettings_progression/overview.html' %}
            {% include 'properties/includes/lettings_progression/phase1.html' %}
            {% include 'properties/includes/lettings_progression/phase2.html' %}
            {% include 'properties/includes/lettings_progression/phase3.html' %}
            {% include 'properties/includes/lettings_progression/phase4.html' %}
        </div>

    </div>
    <!-- end card body -->
</div>
<!-- end card -->

properties/templates/properties/includes/detail/notes.html
{% for instance in notes %}
<tr>
    <td>{{ instance.created|date:"d M Y" }}</td>
    <td>{{ instance.notes }}</td>
    <td class="text-center">
        <span
            data-url="{% url 'properties:edit_progression_notes' instance.id %}" 
            class="text-center text-info pointer js-load-form">
            Edit
        </span>
        /
        <span
            data-url="{% url 'properties:delete_progression_notes' instance.id %}" 
            class="text-center text-danger pointer js-load-form">
            Delete
        </span>
    </td>
</tr>
{% endfor %}

properties/templates/properties/includes/detail/notes_pagination.html
<ul class="pagination pagination-sm mb-0 justify-content-center">
    {% if notes.has_previous %}
        <li class="page-item">
            <button class="page-link text-dark js-notes-pagination" data-url="{% url 'properties:notes_pagination' propertyprocess.id %}?page=1" aria-disabled="true"><span
                    class="mdi mdi-page-first"></span></button>
        </li>
        {% if notes.number == notes_last_page %}
            {% if notes.number != 2 %}
                <li class="page-item">
                    <button class="page-link text-dark js-notes-pagination"
                        data-url="{% url 'properties:notes_pagination' propertyprocess.id %}?page={{ notes.previous_page_number|add:'-1' }}">{{ notes.previous_page_number|add:"-1" }}</button>
                </li>
            {% endif %}
    {% endif %}
        <li class="page-item">
            <button class="page-link text-dark js-notes-pagination"
                data-url="{% url 'properties:notes_pagination' propertyprocess.id %}?page={{ notes.previous_page_number }}">{{ notes.previous_page_number }}</button>
        </li>
    {% else %}
        <li class="page-item disabled">
            <button class="page-link text-light" data-url="?page=1" aria-disabled="true"><span class="mdi mdi-page-first"></span></button>
        </li>
    {% endif %}
    <li class="page-item active" aria-current="page">
        <button class="page-link text-white js-notes-pagination"
            data-url="{% url 'properties:notes_pagination' propertyprocess.id %}?page={{ notes.number }}">{{ notes.number }} <span
                class="sr-only">(current)</span></button>
    </li>
    {% if notes.has_next %}
        <li class="page-item">
            <button class="page-link text-dark js-notes-pagination"
                data-url="{% url 'properties:notes_pagination' propertyprocess.id %}?page={{ notes.next_page_number }}">{{ notes.next_page_number }}</button>
        </li>
        {% if notes.number == 1 %}
            {% if notes_last_page == 2 %}
                <li class="page-item disabled">
                    <button class="page-link text-light" data-url="?page=3">3</button>
                </li>
            {% else %}
                <li class="page-item">
                    <button class="page-link text-dark js-notes-pagination" data-url="{% url 'properties:notes_pagination' propertyprocess.id %}?page=3">3</button>
                </li>
            {% endif %}
        {% endif %}
        <li class="page-item">
            <button class="page-link text-dark js-notes-pagination" data-url="{% url 'properties:notes_pagination' propertyprocess.id %}?page={{ notes_last_page }}"><span
                    class="mdi mdi-page-last"></span></button>
        </li>
    {% else %}
        {% if notes.number == 1 %}
            <li class="page-item disabled">
                <button class="page-link text-light" data-url="?page=2">2</button>
            </li>
            <li class="page-item disabled">
                <button class="page-link text-light" data-url="?page=3">3</button>
            </li>
        {% elif notes_last_page == 2 %}
            <li class="page-item disabled">
                <button class="page-link text-light" data-url="?page=3">3</button>
            </li>
        {% endif %}
            <li class="page-item disabled">
                <button class="page-link text-light" data-url="?page={{ notes_last_page }}"><span class="mdi mdi-page-last"></span></button>
            </li>
    {% endif %}
</ul>

properties/templates/properties/includes/detail/property_chain.html
<div class="card">
    <div class="card-body">
        <h4 class="header-title mb-3 d-inline">Property Chain 
            <span id="saved" class="text-success d-none"><small><span class="mdi mdi-check-circle-outline"></span> Saved</small></span>
            <span id="unsaved" class="text-danger d-none"><small><span class="mdi mdi-close-circle-outline"></span> Not Saved</small></span>
            <span id="error" class="text-danger d-none"><small><span class="mdi mdi-alert-circle-outline"></span> Error - Try Again</small></span>
            <span
                data-url="{% url 'properties:add_property_chain_detail' propertyprocess.id %}"
                class="mb-3 float-right mdi mdi-sticker-plus 
                pointer text-success js-load-form" 
                data-toggle="tooltip"
                data-placement="top"
                title="Add Property"
            ></span>
        </h4>

        <div class="row" id="simple-dragula" data-plugin="dragula" data-handleClass="dragula-handle">
            {% for instance in property_chain %}
                <div class="col-12" id="property_chain{{ instance.order }}" data-pk="{{ instance.pk }}">
                    <div class="card mb-0 mt-1">
                        <div class="card-body">
                            <div class="row w-100 overflow-hidden">
                                <div class="col-10 col-md-5 order-1">
                                    <h5 class="mb-1 mt-1">{{ instance.address_line_1 }}</h5>
                                    <p class="mb-0"> {% if instance.address_line_2 is not None %}{{ instance.address_line_2 }}{% endif %} </p>
                                    <p class="mb-0"> {{ instance.town }} </p>
                                    <p class="mb-0"> {{ instance.postcode }} </p>
                                </div>
                                <div class="col-10 col-md-5 order-3 order-md-2">
                                    <h5 class="mb-1 mt-1">{{ instance.company }}</h5>
                                    <p class="mb-0"> {{ instance.branch }} </p>
                                </div>
                                <div class="col-2 order-2 order-md-3 pr-0">
                                    <span class="d-block dragula-handle float-right"></span>
                                </div>
                                <div class="col-12 order-4 p-0">
                                    <button class="btn btn-sm btn-info float-right js-load-form" data-url="{% url 'properties:property_chain_detail' instance.pk %}"><span class="mdi mdi-arrow-expand-all"></span> Expand</button>
                                </div>
                            </div>
                            <!-- end d-flex -->
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->
            {% endfor %}

        </div>
        <!-- end row-->
        <button id="save-property-order" class="float-right btn btn-sm btn-success mt-2">Save Order</button>
    </div>
    <form id="property-chain-reorder" action="{% url 'properties:save_property_order' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="order" id="order">
    </form>
</div>

properties/templates/properties/includes/detail/property_chain_detail.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center">
            <h4 class="text-white">Property Chain Info</h4>
        </div>
        <h5 class="text-white text-center">Property</h5>
        <p class="text-white text-center mb-0">
            {{ instance.address_line_1 }}
        </p>
        {% if instance.address_line_2 is not None %}
        <p class="text-white text-center mb-0">
            {{ instance.address_line_2 }}
        </p>
        {% endif %}
        <p class="text-white text-center mb-0">
            {{ instance.town }}
        </p>
        <p class="text-white text-center">
            {{ instance.postcode }}
        </p>
        <h5 class="text-white text-center">Agent</h5>
        <p class="text-white text-center mb-0">
            {{ instance.company }}
        </p>
        <p class="text-white text-center mb-0">
            {{ instance.branch }}
        </p>
        <h5 class="text-white text-center">Notes</h5>
        <div class="text-white text-center mb-2 notes">
            {{ instance.chain_notes|linebreaks }}
        </div>
        <hr class="mx-auto border-light w-75">
        <div class="text-center">
            <button data-url="{% url 'properties:edit_property_chain_detail' instance.id %}" class="btn btn-warning mr-2 js-load-form">Edit</button>
            <form method="post" action="{% url 'properties:delete_property_chain_detail' instance.id %}" class="js-submit-form d-inline">
                {% csrf_token %}
                <button type="submit" id="add-button" class="btn btn-danger ml-2">Delete</button>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

properties/templates/properties/includes/detail/property_marketing.html
<!-- Marketing-Information -->
<div class="card">
    <div class="card-body">
        <h4 class="header-title mt-0 mb-3">Marketing Information</h4>
        <div class="text-left">
            <p class="text-muted"><strong>How Did The Seller Hear About Laurels:</strong> <span
                    class="ml-2">{{ propertyprocess.marketing.get_hear_about_laurels_display }}</span>
            </p>
            <p class="text-muted"><strong>How Did The Seller Contact Laurels:</strong><span
                    class="ml-2">{{ propertyprocess.marketing.get_contact_laurels_display }}</span>
            </p>
            <p class="text-muted"><strong>Why Did The Seller Instruct Laurels:</strong> <span class="ml-2">
                {{ propertyprocess.marketing.get_why_did_they_instruct_us_display }} {% if propertyprocess.marketing.why_did_they_instruct_us == "other" %}- {{ propertyprocess.marketing.other }}{% endif %}</span>
            </p>
            <p class="text-muted"><strong>How Was The Applicant Introduced:</strong> <span class="ml-2">
                {{ propertyprocess.marketing.get_applicant_intro_display }}</span>
            </p>
        </div>
    </div>
</div>
<!-- End Marketing Information -->

properties/templates/properties/includes/detail/quick_actions.html
{% load static i18n %}
<button 
    data-url="{% url 'properties:add_valuation' propertyprocess.id %}" data-toggle="tooltip"
    data-placement="top"
    title="Valuation"
    class="mb-1 btn px-2 py-1 {% if propertyprocess.macro_status != 1 %}btn-secondary" disabled{% else %}btn-info js-load-form"{% endif %}>
        <i class="mdi mdi-clipboard-file-outline icon-lg-size"></i>
</button>
<button 
    {% if propertyprocess.sector == "sales" %}
        data-url="{% url 'properties:add_instruction' propertyprocess.id %}"
    {% else %}
        data-url="{% url 'properties:add_lettings_instruction' propertyprocess.id %}"
    {% endif %}
    data-toggle="tooltip"
    data-placement="top"
    title="Instruction"
    class="mb-1 btn px-2 py-1 {% if propertyprocess.macro_status != 2 %}btn-secondary" disabled{% else %}btn-info js-load-form"{% endif %}>
        <i class="mdi mdi-clipboard-text-outline icon-lg-size"></i>
</button>
<button 
    data-url="{% url 'properties:add_reduction' propertyprocess.id %}" data-toggle="tooltip"
    data-placement="top"
    title="Reduction"
    class="mb-1 btn px-2 py-1 {% if propertyprocess.macro_status != 3 %}btn-secondary" disabled{% else %}btn-info js-load-form"{% endif %}>
        <i class="mdi mdi-cash-minus icon-lg-size"></i>
</button>
<button 
    {% if propertyprocess.sector == "sales" %}
        data-url="{% url 'properties:add_offerer' propertyprocess.id %}"
    {% else %}
        data-url="{% url 'properties:add_offerer_lettings' propertyprocess.id %}"
    {% endif %}
    data-toggle="tooltip"
    data-placement="top"
    title="Add Offer"
    class="mb-1 btn px-2 py-1 {% if propertyprocess.macro_status != 3 %}btn-secondary" disabled{% else %}btn-info js-add-offerer"{% endif %}>
        <i class="mdi mdi-offer icon-lg-size"></i>
</button>
<button 
    {% if propertyprocess.sector == "sales" %}
        data-url="{% url 'properties:add_another_offer' propertyprocess.id %}"
    {% else %}
        data-url="{% url 'properties:add_another_lettings_offer' propertyprocess.id %}"
    {% endif %}
    data-toggle="tooltip"
    data-placement="top"
    title="Change Offer"
    class="mb-1 btn px-2 py-1 {% if propertyprocess.macro_status != 3 %}btn-secondary" disabled{% else %}btn-info js-load-form"{% endif %}>
        <i class="mdi mdi-piggy-bank icon-lg-size"></i>
</button>
{% if propertyprocess.macro_status == 3 or propertyprocess.macro_status == 4 %}
    <button 
        data-url="{% url 'properties:withdraw_property' propertyprocess.id %}" data-toggle="tooltip"
        data-placement="top"
        title="Withdraw"
        class="mb-1 btn px-2 py-1 {% if propertyprocess.macro_status == 3 or propertyprocess.macro_status == 4 %}btn-info js-load-form"{% else %}btn-secondary" disabled{% endif %}>
            <i class="mdi mdi-alert-octagon icon-lg-size"></i>
    </button>
{% elif propertyprocess.macro_status == 0 %}
    <button 
        data-url="{% url 'properties:back_on_the_market' propertyprocess.id %}" data-toggle="tooltip"
        data-placement="top"
        title="Back On The Market"
        class="mb-1 btn px-2 py-1 btn-info js-load-large-form">
        <i class="mdi mdi-home-plus icon-lg-size"></i>
    </button>
{% endif %}
<button
    {% if propertyprocess.sector == "sales" %}
        data-url="{% url 'properties:add_deal' propertyprocess.id %}"
    {% else %}
        data-url="{% url 'properties:add_deal_lettings' propertyprocess.id %}"
    {% endif %}
    data-toggle="tooltip"
    data-placement="top"
    title="Add Deal"
    class="mb-1 btn px-2 py-1 {% if propertyprocess.macro_status != 3 %}btn-secondary" disabled{% else %}btn-info js-load-form"{% endif %}>
        <i class="mdi mdi-handshake icon-lg-size"></i>
</button>
<button 
    {% if propertyprocess.sector == "sales" %}
        data-url="{% url 'properties:add_exchange' propertyprocess.id %}"
        title="Add Exchange"
    {% else %}
        data-url="{% url 'properties:add_exchange_lettings' propertyprocess.id %}"
        title="Add Lettings Exchange"
    {% endif %}
    data-toggle="tooltip"
    data-placement="top"
    class="mb-1 btn px-2 py-1 {% if propertyprocess.macro_status != 4 %}btn-secondary" disabled{% else %}btn-info js-load-form"{% endif %}>
        <i class="mdi mdi-home-lock icon-lg-size"></i>
</button>
<button 
    {% if propertyprocess.sector == "sales" %}
        data-url="{% url 'properties:fall_through' propertyprocess.id %}"
    {% else %}
        data-url="{% url 'properties:lettings_fall_through' propertyprocess.id %}"
    {% endif %}
    data-toggle="tooltip"
    data-placement="top"
    title="Fall Though Property"
    class="mb-1 btn px-2 py-1 {% if propertyprocess.macro_status != 4 %}btn-secondary" disabled{% else %}btn-info js-load-form"{% endif %}>
        <i class="mdi mdi-trash-can-outline icon-lg-size"></i>
</button>
{% if propertyprocess.sector == "sales" and propertyprocess.previously_fallen_through is True %}
<button 
    data-url="{% url 'properties:manage_sales_progression' propertyprocess.id %}" data-toggle="tooltip"
    data-placement="top"
    title="Manage Sales Progression"
    class="mb-1 btn px-2 py-1 btn-info js-load-form">
        <i class="mdi mdi-cog-counterclockwise icon-lg-size"></i>
</button>
{% endif %}
{% if propertyprocess.sector == "lettings" and propertyprocess.macro_status == 5 %}
<button 
    data-url="{% url 'properties:re_let' propertyprocess.id %}"
    data-toggle="tooltip"
    data-placement="top"
    title="Re-Let Property"
    class="mb-1 btn px-2 py-1 btn-info js-load-large-form">
        <i class="mdi mdi-clipboard-play-outline icon-lg-size"></i>
</button>
{% endif %}