home/urls.py
from django.urls import path

from home.views import (
    index,
    offer_board,
    deal_progression_overview,
    employee_valuation_list,
    employee_instruction_list,
    employee_reduction_list,
    employee_new_business_list,
    add_primary_processor,
    lettings_add_primary_processor,
)


app_name = "home"
urlpatterns = [
    path("", index, name="home"),
    path("properties/offer-board/", offer_board, name="offer_board"),
    path(
        "progression/",
        deal_progression_overview,
        name="deal_progression_overview",
    ),
    path(
        "ajax/valuations/<profile_id>/",
        employee_valuation_list,
        name="employee_valuation_list",
    ),
    path(
        "ajax/instructions/<profile_id>/",
        employee_instruction_list,
        name="employee_instruction_list",
    ),
    path(
        "ajax/reductions/<profile_id>/",
        employee_reduction_list,
        name="employee_reduction_list",
    ),
    path(
        "ajax/new-business/<profile_id>/",
        employee_new_business_list,
        name="employee_new_business_list",
    ),
    path(
        "ajax/primary-progressor/<propertyprocess_id>/",
        add_primary_processor,
        name="add_primary_processor",
    ),
    path(
        "ajax/lettings-primary-progressor/<propertyprocess_id>/",
        lettings_add_primary_processor,
        name="lettings_add_primary_processor",
    ),
]

lettings/urls.py
from django.urls import path

from lettings.views import (
    managed_properites,
    managed_inactive,
    show_maintenance,
    add_maintenance,
    view_maintenance,
    edit_maintenance,
    add_maintenance_note,
    show_letting,
    add_epc,
    add_gas,
    add_electrical,
    add_renewal,
    maintenance_board,
)


app_name = "lettings"
urlpatterns = [
    path(
        "managed-properties/",
        managed_properites,
        name="managed_properites",
    ),
    path(
        "ajax/managed-properties/<lettings_id>/",
        managed_inactive,
        name="managed_inactive",
    ),
    path(
        "ajax/maintenance/<lettings_id>/",
        show_maintenance,
        name="show_maintenance",
    ),
    path(
        "ajax/add-maintenance/<lettings_id>/",
        add_maintenance,
        name="add_maintenance",
    ),
    path(
        "maintenance/<maintenance_id>/",
        view_maintenance,
        name="view_maintenance",
    ),
    path(
        "ajax/edit-maintenance/<lettings_id>/<maintenance_id>/",
        edit_maintenance,
        name="edit_maintenance",
    ),
    path(
        "ajax/add-maintenance-note/<maintenance_id>/",
        add_maintenance_note,
        name="add_maintenance_note",
    ),
    path(
        "property/<lettings_id>/",
        show_letting,
        name="show_letting",
    ),
    path(
        "ajax/add-epc/<lettings_id>/",
        add_epc,
        name="add_epc",
    ),
    path(
        "ajax/add-gas/<lettings_id>/",
        add_gas,
        name="add_gas",
    ),
    path(
        "ajax/add-electrical/<lettings_id>/",
        add_electrical,
        name="add_electrical",
    ),
    path(
        "ajax/add-renewal/<lettings_id>/",
        add_renewal,
        name="add_renewal",
    ),
    path(
        "maintenance-board/",
        maintenance_board,
        name="maintenance_board",
    ),
]

lettings/views.py
import datetime

from django_otp.decorators import otp_required

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.db.models import Q
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.template.loader import render_to_string

from lettings.forms import (
    MaintenanceForm,
    MaintenanceNotesForm,
    EPCForm,
    ElectricalForm,
    GasForm,
    RenewalDateForm,
)
from lettings.models import LettingProperties, Maintenance, MaintenanceNotes
from properties.forms import RenewalForm
from properties.models import PropertyProcess


@otp_required
@login_required
def managed_properites(request):
    """
    A view to return all managed properties.
    """

    managed_properties_list = LettingProperties.objects.exclude(
        lettings_service_level="intro_only"
    ).order_by(
        "propertyprocess__exchange_and_move__exchange_and_move_lettings__move_in_date"
    )

    active = True
    query = None

    if request.GET:
        if "active" in request.GET:
            active = request.GET["active"]
            if active == "true":
                active = True
            elif active == "false":
                active = False

        managed_properties_list = managed_properties_list.filter(
            is_active=active
        )

        if "query" in request.GET:
            query = request.GET["query"]
            if not query:
                return redirect(reverse("home:deal_progression_overview"))

            queries = (
                Q(propertyprocess__property__postcode__icontains=query)
                | Q(propertyprocess__property__address_line_1__icontains=query)
                | Q(propertyprocess__property__address_line_2__icontains=query)
            )
            managed_properties_list = managed_properties_list.filter(queries)

    managed_properties_list_length = len(managed_properties_list)

    page = request.GET.get("page", 1)

    paginator = Paginator(managed_properties_list, 10)
    last_page = paginator.num_pages

    try:
        properties = paginator.page(page)
    except PageNotAnInteger:
        properties = paginator.page(1)
    except EmptyPage:
        properties = paginator.page(paginator.num_pages)

    context = {
        "managed_properties": properties,
        "last_page": last_page,
        "properties_length": managed_properties_list_length,
        "query": query,
        "active": active,
    }

    template = "lettings/managed_properties.html"

    return render(request, template, context)


@otp_required
@login_required
def managed_inactive(request, lettings_id):
    """
    A view to display a form to allow a property to be made inactive.
    """

    data = dict()

    managed_property = get_object_or_404(LettingProperties, id=lettings_id)

    if request.method == "POST":
        active = request.POST.get("active-selection")
        if active == "False":
            active = False
        else:
            active = True
        managed_property.is_active = active
        managed_property.save()
        data["form_is_valid"] = True
    else:
        active = request.GET.get("active")

    context = {
        "managed_property": managed_property,
        "active": active,
    }
    data["html_modal"] = render_to_string(
        "lettings/includes/managed/active_modal.html",
        context,
        request=request,
    )
    return JsonResponse(data)


@otp_required
@login_required
def show_letting(request, lettings_id):
    """
    A view to display all information on a letting.
    """
    letting = get_object_or_404(LettingProperties, id=lettings_id)

    context = {
        "letting": letting,
    }

    template = "lettings/letting_detail.html"

    return render(request, template, context)


@otp_required
@login_required
def show_maintenance(request, lettings_id):
    """
    A view to display all maintenance for a given property.
    """

    data = dict()

    managed_property = get_object_or_404(LettingProperties, id=lettings_id)

    maintenance_qs = Maintenance.objects.filter(
        lettings_properties=managed_property
    )

    context = {
        "managed_property": managed_property,
        "maintenance_qs": maintenance_qs,
    }
    data["html_modal"] = render_to_string(
        "lettings/includes/managed/maintenance_modal.html",
        context,
        request=request,
    )
    return JsonResponse(data)


@otp_required
@login_required
def view_maintenance(request, maintenance_id):
    """
    A view to show all the detail of a maintenance object.
    """

    maintenance = get_object_or_404(Maintenance, id=maintenance_id)

    context = {
        "maintenance": maintenance,
    }

    template = "lettings/maintenance_detail.html"

    return render(request, template, context)


@otp_required
@login_required
def add_maintenance(request, lettings_id):
    """
    A view to display a form to add maintenance.
    """

    data = dict()

    managed_property = get_object_or_404(LettingProperties, id=lettings_id)

    url = reverse(
        "lettings:add_maintenance",
        kwargs={
            "lettings_id": managed_property.id,
        },
    )

    if request.method == "POST":
        form = MaintenanceForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            instance.lettings_properties = managed_property

            instance.created_by = request.user.get_full_name()
            instance.updated_by = request.user.get_full_name()

            notes = (
                "A maintenance was added by "
                f"{request.user.get_full_name()}."
            )

            instance.save()

            MaintenanceNotes.objects.create(
                maintenance=instance,
                notes=notes,
                created_by=request.user.get_full_name(),
                updated_by=request.user.get_full_name(),
            )

            data["form_is_valid"] = True
        else:
            data["form_is_valid"] = False
    else:
        form = MaintenanceForm()

    context = {"form": form, "managed_property": managed_property, "url": url}
    data["html_modal"] = render_to_string(
        "lettings/includes/managed/add_maintenance_modal.html",
        context,
        request=request,
    )
    return JsonResponse(data)


@otp_required
@login_required
def edit_maintenance(request, lettings_id, maintenance_id):
    """
    A view to display a form to edit maintenance.
    """

    data = dict()

    managed_property = get_object_or_404(LettingProperties, id=lettings_id)

    maintenance = get_object_or_404(Maintenance, id=maintenance_id)

    url = reverse(
        "lettings:edit_maintenance",
        kwargs={
            "lettings_id": managed_property.id,
            "maintenance_id": maintenance.id,
        },
    )

    if request.method == "POST":
        form = MaintenanceForm(request.POST, instance=maintenance)
        if form.is_valid():
            instance = form.save(commit=False)

            instance.updated_by = request.user.get_full_name()

            instance.save()

            data["form_is_valid"] = True
        else:
            data["form_is_valid"] = False
    else:
        form = MaintenanceForm(instance=maintenance)

    context = {"form": form, "managed_property": managed_property, "url": url}
    data["html_modal"] = render_to_string(
        "lettings/includes/managed/add_maintenance_modal.html",
        context,
        request=request,
    )
    return JsonResponse(data)


@otp_required
@login_required
def add_maintenance_note(request, maintenance_id):
    """
    A view to display a form to add maintenance note.
    """

    data = dict()

    maintenance = get_object_or_404(Maintenance, id=maintenance_id)

    if request.method == "POST":
        form = MaintenanceNotesForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            instance.maintenance = maintenance

            instance.created_by = request.user.get_full_name()
            instance.updated_by = request.user.get_full_name()

            instance.save()

            data["form_is_valid"] = True
        else:
            data["form_is_valid"] = False
    else:
        form = MaintenanceNotesForm()

    context = {
        "form": form,
        "maintenance": maintenance,
    }
    data["html_modal"] = render_to_string(
        "lettings/includes/managed/add_maintenance_notes_modal.html",
        context,
        request=request,
    )
    return JsonResponse(data)


@otp_required
@login_required
def add_epc(request, lettings_id):
    """
    A view to display a form to add EPC.
    """

    data = dict()

    managed_property = get_object_or_404(LettingProperties, id=lettings_id)

    url = reverse(
        "lettings:add_epc",
        kwargs={
            "lettings_id": managed_property.id,
        },
    )

    if request.method == "POST":
        form = EPCForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            instance.lettings_properties = managed_property

            instance.created_by = request.user.get_full_name()
            instance.updated_by = request.user.get_full_name()

            instance.save()

            data["form_is_valid"] = True
        else:
            data["form_is_valid"] = False
    else:
        form = EPCForm()

    context = {"form": form, "managed_property": managed_property, "url": url}
    data["html_modal"] = render_to_string(
        "lettings/includes/managed/add_certificate_modal.html",
        context,
        request=request,
    )
    return JsonResponse(data)


@otp_required
@login_required
def add_gas(request, lettings_id):
    """
    A view to display a form to add Gas.
    """

    data = dict()

    managed_property = get_object_or_404(LettingProperties, id=lettings_id)

lettings/templates/lettings/includes/managed/active_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Change Managed Property Active/Inactive</h4>
            <form method="post" action="{% url 'lettings:managed_inactive' managed_property.id %}" class="text-center text-white px-2 js-submit-form custom-form-margin">
                {% csrf_token %}
                <input type="hidden" name="active-selection" value="{{ active }}">
                {% if active == "False" %}
                    <button class="btn btn-danger mb-3 mt-1">Make Inactive</button>
                {% else %}
                    <button class="btn btn-danger mb-3 mt-1">Make Active</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

lettings/templates/lettings/includes/managed/add_certificate_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add Date & Expiry</h4>
            <form method="post" action="{{ url }}" class="text-center text-white px-2 js-submit-form custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.date|as_crispy_field }}
                    </div>
                    <div class="col-12">
                        {{ form.expiry|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Save" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

lettings/templates/lettings/includes/managed/add_maintenance_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center">
            <h4 class="text-white">Add Maintenance</h4>
        </div>
        <div class="text-center text-white">
            <form method="post" action="{{ url }}" class="text-center text-white px-2 js-submit-form custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 col-md-4">
                        {{ form.type|as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-4">
                        {{ form.status|as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-4">
                        {{ form.priority|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-4">
                        {{ form.managed_by|as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-4">
                        {{ form.billing_status|as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-4">
                        {{ form.reported_by|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6 col-md-3">
                        {{ form.target_start_date|as_crispy_field }}
                    </div>
                    <div class="col-6 col-md-3">
                        {{ form.actual_start_date|as_crispy_field }}
                    </div>
                    <div class="col-6 col-md-3">
                        {{ form.target_completion_date|as_crispy_field }}
                    </div>
                    <div class="col-6 col-md-3">
                        {{ form.actual_completion_date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-6">
                        {{ form.cost|as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-6">
                        {{ form.contractor|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-8 offset-md-2">
                        {{ form.summary|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        {{ form.details|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Save" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

lettings/templates/lettings/includes/managed/add_maintenance_notes_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add Note</h4>
            <form method="post" action="{% url 'lettings:add_maintenance_note' maintenance.id %}" class="text-center text-white px-2 js-submit-form custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ form.notes|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Save" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

lettings/templates/lettings/includes/managed/add_renewal_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center text-white">
            <h4 class="text-white">Add Renewal</h4>
            <form method="post" action="{% url 'lettings:add_renewal' managed_property.id %}" class="text-center text-white px-2 js-submit-form custom-form-margin">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 col-md-6">
                        {{ form.fee|as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-6">
                        {{ form.price|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-6">
                        {{ form.date|as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-6">
                        {{ renewal_form.renewal_date|as_crispy_field }}
                    </div>
                </div>
                <div class="my-2 text-center">
                    <button type="submit" class="btn btn-info" id="add-button">{% trans "Save" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.modal-content -->

lettings/templates/lettings/includes/managed/maintenance_modal.html
{% load static i18n %}
<div class="modal-content green-gradient">
    <div class="modal-body">
        <div class="text-center mt-2 mb-3">
            <span><img src="{% static 'custom/images/logo.png' %}" alt="laurels" height="80"></span>
        </div>
        <div class="text-center">
            <h4 class="text-white">Maintenance</h4>
        </div>
        <p class="text-white text-center">Below are the maintenance reports listed for this property.</p>
        <div class="text-center">
            <button class="mx-auto mb-3 btn btn-primary js-hide-form js-load-large-scrollable-form" data-url="{% url 'lettings:add_maintenance' managed_property.id %}">
                Add New Maintenance
            </button>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-sm table-centered mb-0 font-14">
                        <thead class="thead-light">
                            <tr>
                                <th class="text-center">Type</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">View</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for instance in maintenance_qs %}
                            <tr>
                                <td class="text-center">{{ instance.type }}</td>
                                <td class="text-center">{{ instance.get_status_display }}</td>
                                <td class="text-center"><a class="mdi mdi-arrow-expand-all" href="{% url 'lettings:view_maintenance' instance.id %}"></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- end table-responsive-->
            </div>
            <!-- end card-body-->
        </div>
    </div>
</div>
<!-- /.modal-content -->