home/urls.py
from django.urls import path

from home.views import (
    index,
    offer_board,
    deal_progression_overview,
    employee_valuation_list,
    employee_instruction_list,
    employee_reduction_list,
    employee_new_business_list,
    add_primary_processor,
    lettings_add_primary_processor,
)


app_name = "home"
urlpatterns = [
    path("", index, name="home"),
    path("properties/offer-board/", offer_board, name="offer_board"),
    path(
        "progression/",
        deal_progression_overview,
        name="deal_progression_overview",
    ),
    path(
        "ajax/valuations/<profile_id>/",
        employee_valuation_list,
        name="employee_valuation_list",
    ),
    path(
        "ajax/instructions/<profile_id>/",
        employee_instruction_list,
        name="employee_instruction_list",
    ),
    path(
        "ajax/reductions/<profile_id>/",
        employee_reduction_list,
        name="employee_reduction_list",
    ),
    path(
        "ajax/new-business/<profile_id>/",
        employee_new_business_list,
        name="employee_new_business_list",
    ),
    path(
        "ajax/primary-progressor/<propertyprocess_id>/",
        add_primary_processor,
        name="add_primary_processor",
    ),
    path(
        "ajax/lettings-primary-progressor/<propertyprocess_id>/",
        lettings_add_primary_processor,
        name="lettings_add_primary_processor",
    ),
]

lettings/urls.py
from django.urls import path

from lettings.views import (
    managed_properites,
    managed_inactive,
    show_maintenance,
    add_maintenance,
    view_maintenance,
    edit_maintenance,
    add_maintenance_note,
    show_letting,
    add_epc,
    add_gas,
    add_electrical,
    add_renewal,
    maintenance_board,
)


app_name = "lettings"
urlpatterns = [
    path(
        "managed-properties/",
        managed_properites,
        name="managed_properites",
    ),
    path(
        "ajax/managed-properties/<lettings_id>/",
        managed_inactive,
        name="managed_inactive",
    ),
    path(
        "ajax/maintenance/<lettings_id>/",
        show_maintenance,
        name="show_maintenance",
    ),
    path(
        "ajax/add-maintenance/<lettings_id>/",
        add_maintenance,
        name="add_maintenance",
    ),
    path(
        "maintenance/<maintenance_id>/",
        view_maintenance,
        name="view_maintenance",
    ),
    path(
        "ajax/edit-maintenance/<lettings_id>/<maintenance_id>/",
        edit_maintenance,
        name="edit_maintenance",
    ),
    path(
        "ajax/add-maintenance-note/<maintenance_id>/",
        add_maintenance_note,
        name="add_maintenance_note",
    ),
    path(
        "property/<lettings_id>/",
        show_letting,
        name="show_letting",
    ),
    path(
        "ajax/add-epc/<lettings_id>/",
        add_epc,
        name="add_epc",
    ),
    path(
        "ajax/add-gas/<lettings_id>/",
        add_gas,
        name="add_gas",
    ),
    path(
        "ajax/add-electrical/<lettings_id>/",
        add_electrical,
        name="add_electrical",
    ),
    path(
        "ajax/add-renewal/<lettings_id>/",
        add_renewal,
        name="add_renewal",
    ),
    path(
        "maintenance-board/",
        maintenance_board,
        name="maintenance_board",
    ),
]

lettings/models.py
from django.db import models

from common.models import UpdatedAndCreated
from properties.models import PropertyProcess, InstructionLettingsExtra
from users.models import Profile


class LettingProperties(UpdatedAndCreated):
    class Meta:
        ordering = [
            "propertyprocess__property__postcode",
            "propertyprocess__property__address_line_1",
        ]
        verbose_name = "Lettings Property"
        verbose_name_plural = "Lettings Properties"

    BOOL_CHOICES = [(True, "Yes"), (False, "No")]

    SERVICE_LEVEL = [
        (InstructionLettingsExtra.INTRO, "Intro Only"),
        (InstructionLettingsExtra.RENTCOLLECT, "Rent Collect"),
        (InstructionLettingsExtra.FULLYMANAGED, "Fully Managed"),
    ]

    propertyprocess = models.OneToOneField(
        PropertyProcess,
        on_delete=models.CASCADE,
        related_name="lettings_properties",
    )
    lettings_service_level = models.CharField(
        max_length=40, null=True, blank=True, choices=SERVICE_LEVEL
    )
    is_active = models.BooleanField(choices=BOOL_CHOICES, default=True)

    def __str__(self):
        if (
            self.propertyprocess.property.address_line_2 == ""
            or self.propertyprocess.property.address_line_2 is None
        ):
            property_address = "%s, %s" % (
                self.propertyprocess.property.postcode,
                self.propertyprocess.property.address_line_1,
            )
        else:
            property_address = "%s, %s, %s" % (
                self.propertyprocess.property.postcode,
                self.propertyprocess.property.address_line_1,
                self.propertyprocess.property.address_line_2,
            )
        return property_address


class Renewals(UpdatedAndCreated):
    class Meta:
        ordering = [
            "-renewed_on",
            "lettings_properties__propertyprocess__property__postcode",
            "lettings_properties__propertyprocess__property__address_line_1",
        ]
        verbose_name = "Renewals"
        verbose_name_plural = "Renewals"

    lettings_properties = models.ForeignKey(
        LettingProperties, on_delete=models.CASCADE, related_name="renewals"
    )
    renewed_on = models.DateField(null=True, blank=False)
    renewal_date = models.DateField(null=False, blank=False)

    def __str__(self):
        if (
            self.lettings_properties.propertyprocess.property.address_line_2
            == ""
            or self.lettings_properties.propertyprocess.property.address_line_2
            is None
        ):
            property_address = "%s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
            )
        else:
            property_address = "%s, %s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
                self.lettings_properties.propertyprocess.property.address_line_2,
            )
        return property_address


class SecondTwelve(UpdatedAndCreated):
    class Meta:
        ordering = [
            "-date",
            "lettings_properties__propertyprocess__property__postcode",
            "lettings_properties__propertyprocess__property__address_line_1",
        ]
        verbose_name = "Second Twelve"
        verbose_name_plural = "Second Twelve's"

    lettings_properties = models.ForeignKey(
        LettingProperties,
        on_delete=models.CASCADE,
        related_name="second_twelve",
    )
    date = models.DateField(null=False, blank=False)

    def __str__(self):
        if (
            self.lettings_properties.propertyprocess.property.address_line_2
            == ""
            or self.lettings_properties.propertyprocess.property.address_line_2
            is None
        ):
            property_address = "%s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
            )
        else:
            property_address = "%s, %s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
                self.lettings_properties.propertyprocess.property.address_line_2,
            )
        return property_address


class EPC(UpdatedAndCreated):
    class Meta:
        ordering = [
            "-date",
            "lettings_properties__propertyprocess__property__postcode",
            "lettings_properties__propertyprocess__property__address_line_1",
        ]
        verbose_name = "EPC"
        verbose_name_plural = "EPC"

    lettings_properties = models.ForeignKey(
        LettingProperties, on_delete=models.CASCADE, related_name="epc"
    )
    date = models.DateField(null=False, blank=False)
    expiry = models.DateField(null=False, blank=False)

    def __str__(self):
        if (
            self.lettings_properties.propertyprocess.property.address_line_2
            == ""
            or self.lettings_properties.propertyprocess.property.address_line_2
            is None
        ):
            property_address = "%s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
            )
        else:
            property_address = "%s, %s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
                self.lettings_properties.propertyprocess.property.address_line_2,
            )
        return property_address


class Gas(UpdatedAndCreated):
    class Meta:
        ordering = [
            "-date",
            "lettings_properties__propertyprocess__property__postcode",
            "lettings_properties__propertyprocess__property__address_line_1",
        ]
        verbose_name = "Gas"
        verbose_name_plural = "Gas"

    lettings_properties = models.ForeignKey(
        LettingProperties, on_delete=models.CASCADE, related_name="gas"
    )
    date = models.DateField(null=False, blank=False)
    expiry = models.DateField(null=False, blank=False)

    def __str__(self):
        if (
            self.lettings_properties.propertyprocess.property.address_line_2
            == ""
            or self.lettings_properties.propertyprocess.property.address_line_2
            is None
        ):
            property_address = "%s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
            )
        else:
            property_address = "%s, %s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
                self.lettings_properties.propertyprocess.property.address_line_2,
            )
        return property_address


class Electrical(UpdatedAndCreated):
    class Meta:
        ordering = [
            "-date",
            "lettings_properties__propertyprocess__property__postcode",
            "lettings_properties__propertyprocess__property__address_line_1",
        ]
        verbose_name = "Electrical"
        verbose_name_plural = "Electrical"

    lettings_properties = models.ForeignKey(
        LettingProperties, on_delete=models.CASCADE, related_name="electrical"
    )
    date = models.DateField(null=False, blank=False)
    expiry = models.DateField(null=False, blank=False)

    def __str__(self):
        if (
            self.lettings_properties.propertyprocess.property.address_line_2
            == ""
            or self.lettings_properties.propertyprocess.property.address_line_2
            is None
        ):
            property_address = "%s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
            )
        else:
            property_address = "%s, %s, %s" % (
                self.lettings_properties.propertyprocess.property.postcode,
                self.lettings_properties.propertyprocess.property.address_line_1,
                self.lettings_properties.propertyprocess.property.address_line_2,
            )
        return property_address


class Maintenance(UpdatedAndCreated):
    class Meta:
        ordering = [
            "lettings_properties__propertyprocess__property__postcode",
            "lettings_properties__propertyprocess__property__address_line_1",
            "-target_start_date",
        ]
        verbose_name = "Maintenance"
        verbose_name_plural = "Maintenance"

    NEW = "new"
    AWAITING_CONTRACTOR = "awaiting_contractor"
    AWAITING_LANDLORD = "awaiting_landlord"
    AWAITING_TENANT = "awaiting_tenant"
    WAITING_CONTRACTOR = "waiting_contractor"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    FUTURE_JOB = "future_job"

    NO_CHARGE = "no_charge"
    CON_BILLS_TENANT = "con_bills_tenant"
    CON_BILLS_LANDLORD = "con_bills_landlord"
    CON_BILLS_US = "con_bills_us"

    STATUS = [
        (NEW, "New"),
        (AWAITING_CONTRACTOR, "Awaiting Contractor"),
        (AWAITING_LANDLORD, "Awaiting Landlord Consent"),
        (AWAITING_TENANT, "Awaiting Tenant Availability"),
        (WAITING_CONTRACTOR, "Waiting For Contractor"),
        (IN_PROGRESS, "In Progress"),
        (COMPLETED, "Completed"),
        (CANCELLED, "Cancelled"),
        (FUTURE_JOB, "Future Job"),
    ]

    BILLING = [
        (NO_CHARGE, "No Charge"),
        (CON_BILLS_TENANT, "Contractor Bills Tenant"),
        (CON_BILLS_LANDLORD, "Contractor Bills Landlord"),

lettings/templates/lettings/maintenance_detail.html
{% extends "vertical_base.html" %}
{% load static i18n %}
{% load humanize %}

{% block head_title %}{% trans "Maintenance Detail" %}{% endblock head_title %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0 p-0">
                            <li class="breadcrumb-item"><a href="{% url 'home:home' %}"><i class="uil-home-alt"></i> Home</a></li>
                            <li class="breadcrumb-item active"><i class="mdi mdi-home-group"></i> Lettings</li>
                            <li class="breadcrumb-item active"><i class="mdi mdi-home-lock"></i> Managed Properties</li>
                            <li class="breadcrumb-item active"><i class="mdi mdi-home-lock"></i> Maintenance</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Maintenance Detail</h4>
                </div>
            </div>
        </div>     
        <!-- end page title --> 

        <!-- header row -->
        <div class="row">
            <div class="col-sm-12">
                <!-- Maintenance -->
                <div class="card bg-success">
                    <div class="card-body">

                        <div class="row">
                            <div class="col-sm-7">
                                <div class="media">
                                    <div class="media-body">

                                        <h4 class="mt-1 mb-1 text-white">{{ maintenance.lettings_properties.propertyprocess }}</h4>

                                        <ul class="mb-0 list-inline text-light">
                                            <li class="list-inline-item mr-3">
                                                <h5 class="mb-1">{{ maintenance.type }}</h5>
                                                <p class="mb-0 font-13 text-white-50">Type</p>
                                            </li>
                                            <li class="list-inline-item mr-3">
                                                <h5 class="mb-1">{{ maintenance.get_status_display }}</h5>
                                                <p class="mb-0 font-13 text-white-50">Status</p>
                                            </li>
                                            <li class="list-inline-item mr-3">
                                                <h5 class="mb-1">{{ maintenance.managed_by }}</h5>
                                                <p class="mb-0 font-13 text-white-50">Managed By</p>
                                            </li>
                                            <li class="list-inline-item mr-3">
                                                <h5 class="mb-1">{{ maintenance.reported_by }}</h5>
                                                <p class="mb-0 font-13 text-white-50">Reported By</p>
                                            </li>
                                            <li class="list-inline-item mr-3">
                                                <h5 class="mb-1">{{ maintenance.get_billing_status_display }}</h5>
                                                <p class="mb-0 font-13 text-white-50">Billing</p>
                                            </li>
                                        </ul>
                                    </div>
                                    <!-- end media-body-->
                                </div>
                            </div>
                            <div class="col-sm-5">
                                <div class="media">
                                    <div class="media-body">
                                        <h4 class="mt-1 mb-1 font-15 text-white">Quick Actions</h4>
                                        <div id="quick-actions">
                                            <button 
                                                data-url="{% url 'lettings:edit_maintenance' maintenance.lettings_properties.id maintenance.id %}" data-toggle="tooltip"
                                                data-placement="top"
                                                title="Edit Maintenance"
                                                class="btn mb-1 btn-info js-load-large-scrollable-form">
                                                    <i class="mdi mdi-file-document-edit"></i>
                                            </button>
                                            <button 
                                                data-url="{% url 'lettings:add_maintenance_note' maintenance.id %}"
                                                data-toggle="tooltip"
                                                data-placement="top"
                                                title="Add Note"
                                                class="btn mb-1 btn-info js-load-form">
                                                    <i class="mdi mdi-note-multiple-outline"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <!-- end media-body-->
                                </div>
                            </div>
                        </div>
                        <!-- end row -->
                    </div>
                    <!-- end card-body -->
                </div>
                <!--end property / card -->
            </div>
            <!-- end col-->
        </div>
        <!-- end row -->

        <div class="row">
            <div class="col-lg-4">
                <!-- Maintenance-Information -->
                <div class="card">
                    <div class="card-body">
                        <h4 class="header-title mt-0 mb-3">
                            Maintenance Information
                        </span>
                        </h4>
                        <div class="text-left">
                            
                            <p class="text-muted"><strong>Priority:</strong> 
                                <span class="ml-2">
                                    {% if maintenance.priority == 1 %}
                                        <span class="text-danger">Urgent
                                    {% elif maintenance.priority == 2 %}
                                        <span class="text-warning">High
                                    {% elif maintenance.priority == 3 %}
                                        <span class="text-success">Medium
                                    {% elif maintenance.priority == 4 %}
                                        <span class="text-primary">Low
                                    {% endif %}
                                </span>
                            </p>

                            <p class="text-muted"><strong>Target Start Date:</strong> 
                                <span class="ml-2">
                                    {{ maintenance.target_start_date }}
                                </span>
                            </p>

                            <p class="text-muted"><strong>Actual Start Date:</strong>
                                <span
                                    class="ml-2">
                                        {{ maintenance.actual_start_date }}
                                </span>
                            </p>

                            <p class="text-muted"><strong>Target Completion Date:</strong> 
                                <span class="ml-2">
                                    {{ maintenance.target_completion_date }}
                                </span>
                            </p>

                            <p class="text-muted"><strong>Actual Completion Date:</strong> 
                                <span class="ml-2">
                                    {{ maintenance.actual_completion_date }}
                                </span>
                            </p>

                            <p class="text-muted"><strong>Contractor:</strong> 
                                <span class="ml-2">
                                    {{ maintenance.contractor }}
                                </span>
                            </p>

                            <p class="text-muted"><strong>Cost:</strong>
                                {% if maintenance.cost %}
                                    <span class="ml-2">
                                        £{{ maintenance.cost }}
                                    </span>
                                {% endif %}
                            </p>

                            <p class="text-muted mb-1"><strong>Summary...</strong></p>
                            {% if maintenance.summary %}
                                <p class="text-muted mb-1">{{ maintenance.summary }}</p>
                            {% endif %}

                            <p class="text-muted mb-1"><strong>Details...</strong></p>
                            <p class="text-muted">{{ maintenance.details }}</p>

                        </div>
                    </div>
                </div>
                <!-- End Property-Information -->
            </div>
            <!-- end col -->

            <div class="col-lg-8">
                <div class="card">
                    <div class="card-body">
                            <!-- history section -->
                        <h5 class="text-uppercase"><i class="mdi mdi-history mr-1"></i>
                            Maintenance Notes</h5>
        
                        <div class="table-responsive">
                            <table class="table table-borderless table-nowrap mb-0">
                                <thead class="thead-light">
                                    <tr>
                                        <th style="width: 10%;">Date</th>
                                        <th style="width: 20%;" class="text-center">User</th>
                                        <th style="width: 70%;">Notes</th>
                                    </tr>
                                </thead>
                                <tbody id="tbody-history">
                                    {% for instance in maintenance.maintenance_notes.all %}
                                        <tr>
                                            <td>{{ instance.created|date:"D d M Y" }}</td>
                                            <td class="text-center">{{ instance.created_by }}</td>
                                            <td>{{ instance.notes }}</td>
                                        </tr>
                                        {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- end history section -->
                </div>
                <!-- end card body -->
            </div>
            <!-- end col -->
        </div>
        <!-- end row -->

    </div>
    <!-- container -->
    {% include 'partials/base-large-modal.html' %}
    {% include 'partials/base-static-modal.html' %}
{% endblock %}

{% block extra_javascript %}
{{ block.super }}
    <script src="{% static 'lettings/js/lettings-v4.js' %}"></script>
{% endblock %}

lettings/templates/lettings/managed_properties.html
{% extends "vertical_base.html" %}
{% load static i18n %}
{% load humanize %}

{% block head_title %}{% trans "Managed Properties" %}{% endblock head_title %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">

        <div class="row">
            <div class="col">
                <!-- start page title -->
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0 p-0">
                            <li class="breadcrumb-item"><a href="{% url 'home:home' %}"><i class="uil-home-alt"></i> Home</a></li>
                            <li class="breadcrumb-item active"><i class="mdi mdi-home-group"></i> Lettings</li>
                            <li class="breadcrumb-item active"><i class="mdi mdi-home-lock"></i> Managed Properties</li>
                        </ol>
                    </div>
                    <div class="text-center text-sm-left">
                        <h4 class="page-title">Managed Properties</h4>
                    </div>
                </div>
                <!-- end page title -->
            </div>
        </div>
        <!-- end row-->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-2">
                            <div class="col col-md-6 col-lg-4">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search Managed Properties" name="query" id="managed-query">
                                    <div class="input-group-append">
                                        <button class="btn btn-success" type="submit" id="query-search">Find</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="text-right mb-2 mb-md-3">
                                    <div class="btn-group ml-1 mb-2">
                                        <a href="?{% if query %}query={{ query }}&{% endif %}active=true" class="btn btn-sm {% if active %}btn-success text-white{% else %}btn-light text-dark{% endif %}">Active</a>
                                        <a href="?{% if query %}query={{ query }}&{% endif %}active=false" class="btn btn-sm {% if not active %}btn-success text-white{% else %}btn-light text-dark{% endif %}">Inactive</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table class="table table-centered mb-0">
                                <thead class="thead-light">
                                    <tr>
                                        <th>
                                            {% if query %}Search - "{{ query }}"{% endif %}
                                        </th>
                                        <th class="text-center">
                                            Service Level
                                        </th>
                                        <th class="text-center">
                                            Renewal Date
                                        </th>
                                        <th style="width: 7%;" class="text-center">
                                            Maintenance?
                                        </th>
                                        <th style="width: 7%;" class="text-center">
                                            Active?
                                        </th>
                                        <th style="width: 7%;" class="text-center">
                                            Expand
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for instance in managed_properties %}
                                        <tr>
                                            <td style="width: 30%;">
                                                {{ instance }}
                                            </td>
                                            <td class="text-center">
                                                {{ instance.get_lettings_service_level_display }}
                                            </td>
                                            <td class="text-center">
                                                {{ instance.renewals.last.renewal_date }}
                                            </td>
                                            <td class="text-center">
                                                <span class="pointer text-primary link-hover mdi mdi-hammer-wrench font-16 mr-1 js-load-form" data-url="{% url 'lettings:show_maintenance' instance.id %}"></span>
                                            </td>
                                            <td class="text-center">
                                                <span class="pointer text-primary link-hover mdi mdi-home-export-outline font-16 mr-1 js-load-form" data-url="{% url 'lettings:managed_inactive' instance.id %}{% if active %}?active=False{% else %}?active=True{% endif %}"></span>
                                            </td>
                                            <td class="text-center">
                                                <a href="{% url 'lettings:show_letting' instance.id %}"><span class="mdi mdi-arrow-expand-all font-16 mr-1"></span></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col text-center mt-3 mt-sm-2">
                                {% include 'lettings/includes/managed_pagination.html' %}
                            </div>
                        </div>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
        <!-- end row -->         

    </div>
    <!-- container -->
    {% include 'partials/base-static-modal.html' %}
    {% include 'partials/base-large-modal.html' %}
{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'lettings/js/lettings-v4.js' %}"></script>
{% endblock %}